language: cpp
matrix:
  include:
  - env:
    - OCPN_TARGET=xenial
    dist: xenial
    compiler: gcc
    script:
    - "./ci/travis-build-debian.sh"
  - env:
    - OCPN_TARGET=flatpak
    services:
    - docker
    script:
    - "./ci/travis-build-flatpak.sh"
  - env:
    - OCPN_TARGET=fedora
    services:
    - docker
    script:
    - "./ci/travis-build-fedora.sh"
  - env:
    - OCPN_TARGET=osx
    os: osx
    compiler: clang
    script:
    - "./ci/travis-build-osx.sh"

notifications:
  email: false

git:
  depth: 10

deploy:
  provider: script
  script: ci/travis-upload.sh
  skip_cleanup: true
  on:
    branch: master
    tags: false
