language: cpp

  
matrix:
  include:
  - env:
    - OCPN_TARGET=stretch-armhf
    - OCPN_BRANCH=ci
    - OCPN_STABLE_REPO=david-register/ocpn-plugins-stable
    - OCPN_UNSTABLE_REPO=david-register/ocpn-plugins-unstable
    - DOCKER_IMAGE=raspbian/stretch
    services:
    - docker
    script:
    - "./ci/travis-build-raspbian-armhf.sh"
  - env:
    - OCPN_TARGET=buster-armhf
    - OCPN_BRANCH=ci
    - OCPN_STABLE_REPO=david-register/ocpn-plugins-stable
    - OCPN_UNSTABLE_REPO=david-register/ocpn-plugins-unstable
    - DOCKER_IMAGE=opencpn/raspbian-buster:plugin_build_tooling
    services:
    - docker
    script:
    - "./ci/travis-build-raspbian-armhf.sh"


branches:
  only:
    - ci

