language: cpp
os:
- linux
- osx
dist: xenial
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install build-essential
  cmake gettext git-core gpsd gpsd-clients libgps-dev wx-common libwxgtk3.0-dev libglu1-mesa-dev
  libgtk2.0-dev wx3.0-headers libbz2-dev libtinyxml-dev libportaudio2 portaudio19-dev
  libcurl4-openssl-dev libexpat1-dev libcairo2-dev libarchive-dev liblzma-dev libexif-dev;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install cairo libexif xz libarchive;
    wget http://opencpn.navnux.org/build_deps/wx312_opencpn50_macos109.tar.xz;
    tar xJf wx312_opencpn50_macos109.tar.xz -C /tmp;
    export PATH="/usr/local/opt/gettext/bin:$PATH";
    echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile;
    wget http://opencpn.navnux.org/build_deps/Packages.dmg;
    hdiutil attach Packages.dmg;
    sudo installer -pkg "/Volumes/Packages 1.2.5/Install Packages.pkg" -target "/";
  fi
script:
- mkdir -p build
- cd build
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DwxWidgets_CONFIG_EXECUTABLE=/tmp/wx312_opencpn50_macos109/bin/wx-config -DwxWidgets_CONFIG_OPTIONS="--prefix=/tmp/wx312_opencpn50_macos109" -DCMAKE_INSTALL_PREFIX=/tmp/opencpn -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 ..; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake ..; fi
- make
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make create-pkg; ls -la; pwd; fi
addons:
  coverity_scan:
    project:
      name: opencpn-radar-pi/radar_pi
      description: Build submitted via Travis CI
    notification_email: kees@verruijt.net
    build_command_prepend: mkdir -p build; cd build; cmake ..; make clean
    build_command: make
    branch_pattern: coverity_scan
before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export RELEASE_PKG_FILE=$(ls *.pkg); fi
deploy:
  provider: releases
  api_key:
    secure: "PwPgK+fiTtUo6fKF1e3gC3EwqCderV+utXHG/Lf7fXeXvNWFfBvSFXPfbo3lb9NschrbRlwyv5V56ci7hsWzhZCgwlnSrFf/7NWWTKJnWKsaTzdkI+q02pDUkhCed5jgEoDSbxQlf3Dc5ygxMK8gOeqbPZDJ5Z5N6PMtHQogjZu4yqabycC5Bwr2yFmkaNqZUygcKvwD3OOuIO7ysxSDCpuyvS7lHtkKRjlhAJZ/7c/nhZVz0CxUPgiCpzCfjMPF8svAz3uZtwkxGd7nK3cSzMscDrYXjiIP4H8fOiXVRxf7+hEWMor9hBzHcGQODnVI+pb/olgq0At9cEgM/KcUpqoCVvNCUSzNwTgzY61sm7Tu8gSPpW8A7N9wIEPmAmTMu3FWrFSnDJbR6+byrMhg12ahYa9ZBmIDG4TQXR9lmX6J/fUnAD8A7G2RdzPn2y5Jy22L93t77As0tcyPPaLgTpiMlDK7Pkup4LmwnIHNxlRo/zaCmKb/ypUU6QzsZgZU/SiQYOak2rtQ+BSou7qIH02nyjGSPSiPfOIzn1FJvJO8H/Sp/kxcV0BvMAGvwd/HlAmYHk3UwqxJiTYrtFCN2+/6LrxhH/vIIwQ2SbI3zqj3kFrUgcgZbReRi3pkSjqbszAoCXPhhct97AH2aTDZeLzJnykwU0mXjJeQFGHkpMQ="
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    os: osx
    repo: opencpn-radar-pi/radar_pi
