clone_folder: c:\project\opencpn\shipdriver_pi
shallow_clone: false
clone_depth: 10

image:
- Visual Studio 2017

platform: 
# - x64
- Win32

configuration: RelWithDebInfo
test: OFF

install:
  # VS2015 and earlier version - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  
  # set environment variables for wxWidgets
  - set WXWIN=C:\wxWidgets-3.1.2
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
  - cmd: SET PATH=%PATH%;%WXWIN%;%wxWidgets_LIB_DIR%;C:\Program Files (x86)\Poedit\Gettexttools\bin;

  # install dependencies:
  - choco install poedit

  # Download and unzip wxwidgets
  - ps: Start-FileDownload http://opencpn.navnux.org/build_deps/wxWidgets-3.1.2.7z
  - cmd: 7z x wxWidgets-3.1.2.7z -o%WXWIN% > null

  # some debugging information
  # - cmake --help
  # - set Displays sensitive password!

  # build wxWidgets - Disabled as we provide prebuilt WX to save time
  #- cmd: cd %WXWIN%\build\msw\
  #- cmd: nmake -f makefile.vc BUILD=release SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_
  #- cmd: nmake -f makefile.vc BUILD=debug SHARED=1 CFLAGS=/D_USING_V120_SDK71_ CXXFLAGS=/D_USING_V120_SDK71_

before_build:
  - cd c:\project\opencpn\shipdriver_pi
  - mkdir build
  - cd build
#  - ps: Start-FileDownload http://opencpn.navnux.org/build_deps/OpenCPN_buildwin-4.99a.7z
#  - cmd: 7z x -y OpenCPN_buildwin-4.99a.7z -oc:\project\opencpn\buildwin
  - cmake -T v141_xp ..

build_script:
  - cmake -G "Visual Studio 15 2017" --config RelWithDebInfo  ..
  - cmake --build . --target tarball --config RelWithDebInfo
  - choco install git
  - py -m ensurepip
  - py -m pip install -q setuptools
  - py -m pip install -q cloudsmith-cli
  - bash ./upload.sh
  - PATH=C:\Python38;%PATH%
  - python --version
  - python -m pip install -q cryptography
  - cd ..\ci
  - python git-push

artifacts:
  - path: 'build\*.exe'
    name: installer

deploy:
  description: 'release created by AppVeyor CI'
  provider: GitHub
  auth_token:
    secure: 7c7f490c533dab87ca6592dcae9d5cd158ad0f58
  artifact: installer,portable
  draft: true
  prerelease: true
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    APPVEYOR_REPO_TAG: true # deploy on tag push only
